"""Initial migration

Revision ID: c668d7ab965f
Revises: 
Create Date: 2024-12-03 19:52:57.228484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c668d7ab965f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('padelspeler_transaction')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aankondiging_datum', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('aankondiging_tijd', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'zoekertje', ['listing_id'], ['listing_id'])
        batch_op.drop_column('view_nr')

    with op.batch_alter_table('padelspeler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calender_integration', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('frequent_play_day', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('frequent_play_start_time', sa.Time(), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('attribute2')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ontvanger_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('betaler_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'padelspeler', ['betaler_id'], ['padelspeler_id'])
        batch_op.create_foreign_key(None, 'padelspeler', ['ontvanger_id'], ['padelspeler_id'])

    with op.batch_alter_table('zoekertje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_sent', sa.Boolean(), nullable=True))
        batch_op.alter_column('datum',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zoekertje', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('datum',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('notification_sent')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('betaler_id')
        batch_op.drop_column('ontvanger_id')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attribute2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('padelspeler', schema=None) as batch_op:
        batch_op.drop_column('frequent_play_start_time')
        batch_op.drop_column('frequent_play_day')
        batch_op.drop_column('calender_integration')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_nr', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('aankondiging_tijd')
        batch_op.drop_column('aankondiging_datum')
        batch_op.drop_column('listing_id')

    op.create_table('padelspeler_transaction',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('padelspeler_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['padelspeler_id'], ['padelspeler.padelspeler_id'], name='padelspeler_transaction_padelspeler_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], name='padelspeler_transaction_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('transaction_id', 'padelspeler_id', name='padelspeler_transaction_pkey')
    )
    # ### end Alembic commands ###
